Draft: (#140) Added parameters to control /etc/security/faillock.conf
simp/pupmod-simp-pam pull request #141
Opened 2023-12-19 15:44 UTC by michael-riddle

2024-01-11 16:56 UTC, michael-riddle commented
@silug suggested an additional test to make sure the format of the in-line faillock params are working as expected.

He also suggested refactoring the OS version comparisons to be more hiera-driven. Will need to get some clarification on what he meant by this before attempting to refactor.

2024-01-29 20:48 UTC, silug requested changes

2024-01-29 20:48 UTC, silug commented on manifests/config.pp
> +  if ($facts['os']['release']['major'] > '7') and ($pam::manage_faillock_conf) {
This was the bit that I was referring to when I said something about using hiera defaults.  This comparison probably won't do what you want on Amazon Linux, for example.

2024-01-29 20:48 UTC, silug commented on spec/classes/config_spec.rb
> +        if os_facts[:os][:release][:major] <= '7'
This will have similar problems.

2024-01-29 22:04 UTC, silug approved these changes

2024-01-29 22:14 UTC, merged